### ISSUE TITLE
Validate mc4plus c-shape support in IPTS

### ISSUE THREAD

**Issue by davidetome** [icub-tech-iit/ipts#13]
## Task description
I need to test the support added in IPTS  testing the new 10` mc4plus c-shape` coming from the supplier.: 

- https://github.com/icub-tech-iit/purchases/issues/2043#issuecomment-1418886581

cc @pattacini @maggia80 @Fabrizio69 

## Definition of Done
- [x] IPTS SW validated
- [x] boards tested
- [x] new release of IPTS produced

**Comment by davidetome** [comment]
Ciao @Fabrizio69 ,

 are the new mc4plus c-shape arrived? Just to now, and plan this activity w/ @Nicogene 👍🏻 

cc @pattacini @maggia80

**Comment by davidetome** [comment]
/remind me to plan this issue on Apr 16

**Comment by Fabrizio69** [comment]
> Ciao @Fabrizio69 ,
> 
> 
> 
>  are the new mc4plus c-shape arrived? Just to now, and plan this activity w/ @Nicogene 👍🏻 
> 
> 
> 
> cc @pattacini @maggia80 

Hi @davidetome , I asked yesterday for the delivery date (see [purchase issue](https://github.com/icub-tech-iit/purchases/issues/2043#issuecomment-1499215217))

**Comment by davidetome** [comment]
Today I tested 3 new boards w/ success, see 

- https://github.com/icub-tech-iit/proto/issues/2251#issuecomment-1551358334

Tomorrow I'll finalize the validation and I'll generate a new release of IPTS

cc @Nicogene @pattacini

**Comment by davidetome** [comment]
Done w/ this PR : 

- https://github.com/icub-tech-iit/ipts/pull/19

Going to produce the new releease
