### ISSUE TITLE
Verify status of motor testing suite: test hall sensors

### ISSUE THREAD

**Issue by Fabrizio69** [icub-tech-iit/ipts#20]
## Task Description
In reference to the [previous issue](https://github.com/icub-tech-iit/ipts/issues/17#issuecomment-1549239056) the BLDC motor codes (7117,7116) are supported in ipts from this release:

-  https://github.com/icub-tech-iit/ipts/releases/tag/v1.1.0

but there is a problem: as indicated in the description of each code, these are motors without hall sensor

![image](https://github.com/icub-tech-iit/proto/assets/12031391/0ebaff25-b143-4768-805b-da23c940d315)
![image](https://github.com/icub-tech-iit/proto/assets/12031391/3eb19983-243f-4174-8262-7b2210a89526)

while in the test report we can see :

![image](https://github.com/icub-tech-iit/proto/assets/12031391/4dfb2069-c524-4733-85f5-4d71bda617db)

## Definition of Done
Verification done and issue solved

**Comment by pattacini** [comment]
Hi @Nicogene

We need to plan for it.

cc @davidetome

**Comment by davidetome** [comment]
I simply need to remove the test from the XML configuration file.

For the next codes to be added, I suggest opening an issue in https://github.com/icub-tech-iit/ipts describing : 

- Code / Description
- List of tests
- Images / Instructions needed for the test

cc @Nicogene @pattacini  @Fabrizio69

**Comment by pattacini** [comment]
>I simply need to remove the test from the XML configuration file.

See #21 for this.

**Comment by Fabrizio69** [comment]
> I simply need to remove the test from the XML configuration file.
> 
> For the next codes to be added, I suggest opening an issue in https://github.com/icub-tech-iit/ipts describing :
> 
>     * Code / Description
> 
>     * List of tests
> 
>     * Images / Instructions needed for the tests
> 
> 
> cc @Nicogene @pattacini @Fabrizio69

Thanks a lot @davidetome , remember that the motors are cod.7117 and cod.7116 (without hall sensors, from [WinGST description](https://github.com/icub-tech-iit/ipts/issues/20#issue-1722048313))

**Comment by davidetome** [comment]
Ciao @Fabrizio69 , 

the motor is already present (See the tested code in the repo main page below) , the problem as already said is that you're using a very old rev of IPTS as the report above says...

- https://github.com/icub-tech-iit/ipts

Anyway let me produce the new release w/ the bug fix of the motor 7117 (I will do it this afernoon) and please install the latest release!

cc: @Nicogene @pattacini

**Comment by Fabrizio69** [comment]
... grazie @davidetome !!!

**Comment by davidetome** [comment]
📢  The new  release of IPTS is available : 

- https://github.com/icub-tech-iit/ipts/releases/tag/v1.4.1

Please remove any old installations, and install it.

cc @Nicogene @pattacini @Fabrizio69 @GiacomoVassallo13
