### ISSUE TITLE
FAP - add test support

### ISSUE THREAD

**Issue by davidetome** [icub-tech-iit/ipts#25]
As per the title, we need to add test support for `FAP` boards.

```[tasklist]
### Tasks
- [x] test firmware released
- [x] new IPTS release produced
```

cc @Nicogene @maggia80 @marcoaccame

**Comment by davidetome** [comment]
adding test support

- https://github.com/icub-tech-iit/ipts/compare/master...davidetome:ipts:fix/add-fap

to be checked an PR opened

**Comment by davidetome** [comment]
PR opened, newIPTS release wi;; be produced as soon as it's merged

- https://github.com/icub-tech-iit/ipts/pull/26

cc @pattacini @Nicogene

**Comment by davidetome** [comment]
The new IPTS release which adds FAP5 test support has been produced : 

- https://github.com/icub-tech-iit/ipts/releases/tag/v1.5.0

cc @pattacini @Nicogene @maggia80 @Fabrizio69

**Comment by pattacini** [comment]
Sw released at:
- https://github.com/icub-tech-iit/ipts/releases/tag/v1.5.0
