### ISSUE TITLE
AMC-BLDC - prepare test firmware project

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/ipts#30]
## Task description
As per the title , prepare the `embot` based test project in Keil (`icub-firmware`) w/ a very basic first test on the CAN bus.

## Definition of Done
- [x] project created
- [x] project tested
- [x] PR opened in `icub-firmware devel`

cc @Nicogene @marcoaccame @pattacini @fgarini

**Comment by davidetome** [comment]
HW retrieved. just missing the programming cable.

Test project created, faced some compiling issues : 

- https://github.com/davidetome/icub-firmware/commit/47f2acef92c6f25edb0dbb8983a3d30ee2b1cd4e

cc @Nicogene @marcoaccame @sgiraz

**Comment by davidetome** [comment]
Test on `CAN` communication implemented and tested : 

https://github.com/icub-tech-iit/ipts/assets/6638215/7cf5af99-b5f4-433f-8c5b-260832b3d67a

Here is the related `PR` : 

- https://github.com/robotology/icub-firmware/pull/441

cc @Nicogene @marcoaccame @sgiraz @pattacini
