### ISSUE TITLE
2FOC - add support for version K

### ISSUE THREAD

**Issue by davidetome** [icub-tech-iit/ipts#32]
## Task description
We need to update the test of `2FOC` to support `3336.K` revision which implements a higher overcurrent limit (31A) and causes relative tests to fail : 

- test I su ponte CH 1
- test I su ponte CH 2

## Definition of Done
- [x] test updated
- [x] new IPT release produced

cc @Nicogene @maggia80  @Fabrizio69

**Comment by davidetome** [comment]
Ciao @Fabrizio69 , do you know whin the test jig will be available once returned from the provider (EES)?

Just to let us plan this activity 👍🏼 

cc @valegagge @maggia80

**Comment by valegagge** [comment]
We are waiting the Merello's answer.

**Comment by davidetome** [comment]
I left the message in the draft folder accidentally; just sent support request.

![image](https://github.com/icub-tech-iit/ipts/assets/6638215/de426ab0-ba19-44f2-9473-8431b4236214)

**Comment by davidetome** [comment]
Andrea Merello (author of the test FW) replied : 

> Ciao Davide,
> 
> Tutto bene, te ?
> 
> Allora cosi' su due piedi non sono sicuro: e' passato molto tempo da quando ci ho messo mano e quindi potrei ricordare male..
> 
> .. comunque, stiamo parlando della protezione hardware a 21A, che e' stata aumentata a 31? Secondo me il FW guardava appunto, se scattava facendo passare un opportuna corrente e poi il FW controllava se era scattata e lo riportava al SW utente.
> 
> Cioe', non mi verrebbe da dire che ci sia una soglia da regolare nel software, ma bensi' che si debbano creare le condizioni fisiche per far passare piu' di 31A (resistenze? alimentatore?) durante il test, in modo che il FW rilevi l'intervento della protezione..
> 
> Pero' come ti dicevo i miei ricordi sono un po' sbiaditi.. Verifico e ti dico qualcosa di piu' affidabile..
> 
> Andrea
> 
> Ti so dire qualcosa..

cc @valegagge

**Comment by maggia80** [comment]
io proverei portando la tensione di test a 60V se l'alimentatore che utilizziamo per i test lo consente. Così da verificare di riuscire a far scattare la soglia.

**Comment by davidetome** [comment]
To update this issue with the Merello consideration, I received 2 mail more : 

> Allora, ho fatto qualche verifica:
> 
> Relativamente alla fase2 del test (*) ti direi che, come avevi dedotto tu, non c'e' alcuna regolazione nel FW. Se non erro, ma magari controlla anche te che non ci siano stati cambiamenti nell HW attuale rispetto a queste informazioni in mio possesso, il test viene effettuato con scheda completamente montata, e con collegate 3 resistenze di carico, a stella sulle fasi, da 0.75ohm l'una.
> 
> Durante il test di protezione il FW fa girare la PWM tra due delle tre fasi, con l'alimentatore a 45V, e verifica che la protezione sia scattata.
> 
> Essendo il carico resistivo, probabilmente il fatto che venga emessa PWM e non una tensione continua (pari al 100% della tensione di alimentazione) potrebbe non essere particolarmente rilevante: se la protezione e' veloce (dovrebbe!) allora potrebbe scattare al primo diclo di PWM, pero' questo e' da verificare (non mi ricordo ovviamente.. ** ).
> 
> Comunque con 45V di alimentazione e un collegamento tramite 2 X 0.750ohm tra le fasi si ottiene una corrente di 30A (45/(0.750*2)), che poi non sara' mai esatta a causa delle resistenze parassite, delle tolleranze ecc.
> 
> Se cosi' fosse, e se davvero il fatto che venga emessa PWM invece di una continua non fosse particolarmente rilevante, come ho supposto sopra, allora la corrente in questione sarebbe decisamente sufficiente per far scattare la protezione a 21A, ma troppo al limite per quella da 31A.
> 
> Potrebbe essere sufficiente scendere un po' con le resistenze di carico (ma potrebbe essere necessario inserire le resistenze piu' basse solo in questa fase del test, per non farne fallire altre), oppure in linea teorica salire un po' con la tensione dell'alimentatore, pero' bisogna vedere se il MAX ammissibile dalla 2FOC e' sufficiente per far scattare la protezione - che se ricordo bene aveva una soglia di intervento piuttosto spannometrica (considera che per far passare 40A ci vorrebbero 60V).
> 
> Alla fine della fiera, intervenendo sul FW si puo far poco: anche se il fatto che venga emessa PWM (**) si rivelasse rilevante, e modificassimo il FW per andare al 100%, sospetto che le condizioni di test attuali sarebbero troppo al pelo per far scattare in modo reliable la protezione a 31A. Secondo me la cosa piu' semplice e' fare quella specifica fase del test (che tralaltro e' l'ultima) cambiando le resistenze di carico collegate alle morsettiere con resistenze un po' piu' basse, ad esempio con resistenze intorno agli 0.56 ohm si dovrebbe tirare una corrente teorica di 40A, che dovrebbe essere sufficiente per far scattare la protezione.
> 
> .. Domanda: tutto questo riguarda la fase 2(*); ma vedo che anche nella fase 1 c'e' un test di protezione di corrente.. Questo passa? credo che le resistenze di carico sul JIG usato nella fase 1 siano diverse, ma non sono sicuro di sapere il valore esatto. Da schematico dovrebbero essere 0.470 ohm, e sarebbero quindi sufficienti a far scattare la protezione a 31A, ma dalle foto del jig sembrano 22ohm.. boh..
> 
> Andrea

and 

> Per quanto riguarda l'ipotesi di alzare l'alimentazione (alternativamente ad abbassare le resistenze): mi dice Claudio che fino a 50V siamo tranquilli, piu' su e' da verificare perche' i mosfet sono da 100V, ma gli alimentatori no.
> 
> Guardando lo schema mi par di capire che il DC/DC integrato arrivi a 75V, quindi forse si puo' salire ancora (60V?) dato che abbiamo solo carichi resistivi che non "rinculano"; non mi pare di vedere altre criticita', ma e' da provare pero' con cautela su qualche esemplare che si e' disposti anche a sacrificare nella peggiore delle ipotesi.
> 
> Poi ovviamente ci vuole un alimentatore da banco idoneo, ed e' da vedere che non ci siano problemi "legali" (c'era una soglia di 50V sotto la quale si considerava tutto bassa tensione e safe, e sopra la quale bisognva prendere maggiori precauzioni o ricordo male?)
> 
> Per il resto, se il firmware si arrabbiasse per un overvoltage (in realta' da un occhiata veloce al codice non mi pare che controlli) allora si che ci si potrebbe metter mano per cambiare la soglia di tensione.
> 
> Andrea
> 

cc @valegagge @maggia80

**Comment by davidetome** [comment]
Today I tested the current protection putting the 2 channels of the Power Sypply in parallel both @60 Vdc 20A.

The test was successful but I did it only on the Channel 1 : 

[2FOC sn0 31-5-2024 16.58.13 N11.txt](https://github.com/user-attachments/files/15515545/2FOC.sn0.31-5-2024.16.58.13.N11.txt)

In fact, I noticed that one nail is missing on the test jig and the flashing of the test FW fails : 

![PXL_20240531_145948874](https://github.com/icub-tech-iit/ipts/assets/6638215/b359b89a-baca-41fd-ac64-872e78c6fdf3)

On Monday I will retrieve a nail and test both channels, if all is ok I will open a pull request w/ the new indications 👍🏼 

cc @valegagge @maggia80 @Fabrizio69

**Comment by davidetome** [comment]
⚠️ unfortunately not only the nail is missing but its housing has to be replaced since the nail can't insert correctly.

In order to validate the test I could try with the other test jig that should be ok.

@Fabrizio69 I will open an issue in `proto` asking support to replace the nail and its housing 👍🏼 

cc @valegagge @maggia80

**Comment by Fabrizio69** [comment]
Hi @davidetome, do you know any info on the missing nail?
From test JIG BOM (cod.4569.D) I can find the Testing equipment for 2FOC boards (cod.4573.A) where the JJ26 code is 3138

![image](https://github.com/icub-tech-iit/ipts/assets/12031391/602e79ae-70ba-42b1-80db-1de92355abe2)

From WinGST, I can verify that cod.3138 is not available (no purchase for this code):

![image](https://github.com/icub-tech-iit/ipts/assets/12031391/2122507d-f751-4f8a-a30f-39a53ee47f55)

Do you have any samples to use for this replacement?

At the moment I have no information to proceed with the purchase, if you look at the information of cod.3138 you will not see any commercial supplier or manufacturer (only IIT): 

![image](https://github.com/icub-tech-iit/ipts/assets/12031391/63d46c85-d0be-42a9-860f-b66a18289523)

From the attached technical documentation it is possible to choose one of these:

![image](https://github.com/icub-tech-iit/ipts/assets/12031391/731258ae-cb8a-4536-a0f8-2fcd7afdb17a)

Do you have info to select the correct one?

cc: @valegagge @maggia80

**Comment by Gandoo** [comment]
ciao @Fabrizio69  ho sostituito la camica  danneggiata con questa  https://it.rs-online.com/web/p/puntali-di-test/2615238?searchId=36852eb7-8ed2-4141-8154-3f9582f0b284&gb=s 

qua ci sono gli spilli compatibili https://docs.rs-online.com/13e5/A700000009169812.pdf

**Comment by davidetome** [comment]
Ho recuperato un ago e tutto funziona!

Grazie @Gandoo 🏅 

cc @Fabrizio69 @valegagge

**Comment by davidetome** [comment]
Ho recuperato un ago e tutto funziona!

Grazie @Gandoo 🏅 

cc @Fabrizio69 @valegagge

**Comment by davidetome** [comment]
Dopo la riparazione di @Gandoo ho provato due schede e tutto funziona : 

[2FOC sn1561 6-6-2024 10.53.39 N45.txt](https://github.com/user-attachments/files/15613719/2FOC.sn1561.6-6-2024.10.53.39.N45.txt)
[2FOC sn1573 6-6-2024 11.14.51 N48.txt](https://github.com/user-attachments/files/15613720/2FOC.sn1573.6-6-2024.11.14.51.N48.txt)

Ho notato peró che settando la tensione a 60 Vdc la protezione interviene anche con un assorbimento massimo impostato sull' alimentatore ad 1A; questo molto probabilmente é dovuto al fatto che la protezione interviene al primo ciclo di PWM, come[ diceva Merello](https://github.com/icub-tech-iit/ipts/issues/32#issuecomment-2115110508), e quindi troppo velocemente per la limitazione dell' alimentatore.. @maggia80 che pensi?
Anche se in teoria la  corrente massima di un canale é 20A.

@maggia80 , aspetto tuo feedback per modificare istruzioni e fare nuova release.

⚠️ @Fabrizio69 @Miche19 La golden board (3336.F SN 1499)invece risulta guasta (non si programma neanche) ed il programmatore che era nell' atrezzatura non funziona piú da stamattina. Da sostituire con quello nuovo datoim oggi da @Miche19 (da scaricare)  : 

![PXL_20240606_105906633](https://github.com/icub-tech-iit/ipts/assets/6638215/234bec8a-f35a-4853-a179-df309a78b0a9)

**Comment by Fabrizio69** [comment]
Grazie @davidetome, volevo riportare queste tue osservazioni sulla BOM dell'attrezzatura di collaudo, in modo che in futuro quando la si utilizzerà per fare il check di ciò che i fornitori ci restituiscono, ci siano le info corrette. Mi accorgo che in nessuna issue abbiamo citato codice, revisione e S/N dell'attrezzatura. So che hai fatto le prove su due attrezzature, una ufficiale ed una no. Immagino tu ti stia riferendo a quella ufficiale cioè il cod.4569.D S/N:001, giusto?

cc: @Miche19

**Comment by Gandoo** [comment]
istruzioni per il montaggio link https://docs.rs-online.com/13e5/A700000009169812.pdf  

cc @Fabrizio69

**Comment by davidetome** [comment]
> Grazie @davidetome, volevo riportare queste tue osservazioni sulla BOM dell'attrezzatura di collaudo, in modo che in futuro quando la si utilizzerà per fare il check di ciò che i fornitori ci restituiscono, ci siano le info corrette. Mi accorgo che in nessuna issue abbiamo citato codice, revisione e S/N dell'attrezzatura. So che hai fatto le prove su due attrezzature, una ufficiale ed una no. Immagino tu ti stia riferendo a quella ufficiale cioè il cod.4569.D S/N:001, giusto?
> 
> cc: @Miche19

ciao @Fabrizio69 , si quella rientrata da EES 4569.C SN/001

cc @Miche19

**Comment by davidetome** [comment]
Ciao @Miche19 , 

 l' etichetta posta sull' attrezzatura riporta la vrsione C, sarebbe da sostituire in D.
Sulla scatola che la contiene era giá stata modificata a mano, magari ristampi anche quella... 👍🏼 

cc @Fabrizio69

**Comment by davidetome** [comment]
> Ciao @davidetome, dobbiamo consegnare al fornitore, l'attrezzatura di collaudo che hai verificato con le schede 2FOC rev.K (cod.3336.K, vedi https://github.com/icub-tech-iit/purchases/issues/2722#issuecomment-2151758470 di @maurizbo), ti chiederei quindi di consegnarla (con il programmatore e la Golden Board che hai sostituito) a @Miche19 in modo che possa organizzarne la spedizione. Grazie mille

ok @Fabrizio69 , domani porto tutto a @Miche19 👍🏼 

@maggia80 conferma le mie [considerazioni](https://github.com/icub-tech-iit/ipts/issues/32#issuecomment-2152048633), posso efettuae la modifica e rilasciare la nuova release.

cc @valegagge

**Comment by davidetome** [comment]
Ho modificato le istruzioni per i test in oggetto, riprovato tutto con nuova [Golden Board](https://github.com/icub-tech-iit/tickets/issues/3550)  : 

Test Report : 

[2FOC sn1561 12-6-2024 15.7.13 N81.txt](https://github.com/user-attachments/files/15806338/2FOC.sn1561.12-6-2024.15.7.13.N81.txt)

PR
- https://github.com/icub-tech-iit/electronics-legacy/pull/79

⚠️ @fgarini @andresoll @maggia80 non ho i diritti su questa repo qualcuno puó mergiare? 

Generato nuovo installer e rilasciato nuova release `IPTS:`

- https://github.com/icub-tech-iit/ipts/releases/tag/v1.0.4

Ho riconsegnato attrezzatura , nuova [golden boad](https://github.com/icub-tech-iit/tickets/issues/3550) e [nuovo programmatore](https://github.com/icub-tech-iit/ipts/issues/32#issuecomment-2152048633) a @Miche19 

cc @valegagge @Fabrizio69 @maggia80

**Comment by valegagge** [comment]
Hi @davidetome ,

se non mi sbaglio, nella PR che hai fatto c'e'un errore di copia incolla per il canale 2.

![image](https://github.com/icub-tech-iit/ipts/assets/4233231/baf24420-8771-4757-972e-5e89999c6720)

**Comment by davidetome** [comment]
> Hi @davidetome ,
> 
> se non mi sbaglio, nella PR che hai fatto c'e'un errore di copia incolla per il canale 2.
> 
> ![image](https://private-user-images.githubusercontent.com/4233231/339254715-baf24420-8771-4757-972e-5e89999c6720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjY0MjEsIm5iZiI6MTcxODI2NjEyMSwicGF0aCI6Ii80MjMzMjMxLzMzOTI1NDcxNS1iYWYyNDQyMC04NzcxLTQ3NTctOTcyZS01ZTg5OTk5YzY3MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDgwODQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjUxODVkMTdjYmQxYTE0NmViNjFiMjY1Y2NjMTdkZjk0OTE3Y2QzNzM0Zjg4OGQyNDBjNDI5YjlmNmY1OTdkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vMcGMJDNbQIK3DEY17ZPocHsG68R1d8gn_nbBrQ3NX8)

@valegagge e'giusto...faccio mettere a 60Vdc solo per i due test di protezione corrente
poi riporto a 45 per sicurezza

**Comment by Fabrizio69** [comment]
Ciao @davidetome , visto il [tuo commento precedente](https://github.com/icub-tech-iit/ipts/issues/32#issuecomment-2163243836), ho generato su WinGST una nuova revisione per l'attrezzatura di collaudo. Nel dettaglio:
- Ho creato il nuovo cod.4569.E,
- Ho duplicato la BOM del cod.4569.D e l'ho associata al nuovo cod.4569.E.
- Ho modificato la BOM cod.4569.E sostituendo la golden board: era rev.F, diventa rev.K (ho riportato tutto nel commento della BOM)
-  Ho obsoletizzato l'ormai vecchio cod.4569.D ed impostato il sostituito da con il cod.4569.E.

A questo punto @Miche19 potrà gestire i vari movimenti di magazzino utilizzando questa nuova revisione (E) dell'attrezzatura di collaudo (cod.4569). Grazie a tutti

cc: @valegagge

**Comment by valegagge** [comment]
Dod satified. closing.

**Comment by maurizbo** [comment]
Ciao @valegagge il fornitore MW-FEP che sta collaudando le 2FOC mi chiede ció

_Buongiorno Sig. Borgagni, 
la presente per chiederle se avreste a disposizione i driver di WINDOWS 11 per l'USB CAN. 
Resto in attesa di un Vs. gentile riscontro. 
Grazie 
Cordiali Saluti 
Matteo Sain_

MW.FEP S.p.A. 

Cosa gli debbo rispondere?

**Comment by valegagge** [comment]
Ciao Mauri,
immagino che i driver a cui si riferiscano siano per lo scatolotto [ESD CAN](https://esd.eu/en/products/can-usb-3-fd?sku=C.2076.62&cHash=f0d44679601153c5f26be502e3e70acd).

I driver per ESD CAN sono uguali sia per win 10 che 11. Li trovi a [questa pagina](https://esd.eu/fileadmin/esd/software/drivers/can/windows/usb3/can_usb3_win64_281.zip). 

Puoi anche chiedere supporto a @MSECode .

ciao
