### ISSUE TITLE
Add the board list in the ipts README.md

### ISSUE THREAD

**Issue by Fabrizio69** [icub-tech-iit/ipts#4]
## Task Description
As discussed with @pattacini and @davidetome, it's useful to add, in the README.md file (see the [ipts repo](https://github.com/icub-tech-iit/ipts)), the list of boards that this suite can test.

## Definition of Done
The list of electronic boards is added in the README.md file

**Comment by davidetome** [comment]
Done w/ this [commit](https://github.com/icub-tech-iit/ipts/commit/74cbcebbc1295f434a0c08d792a29113501f97d3)
