### ISSUE TITLE
ETS - 2FOC - add Pickit4 support

### ISSUE THREAD

**Issue by davidetome** [icub-tech-iit/ipts#8]
## Task description
We need to add support for the `Pickit4` debugger in the `ETS` test suite for `2FOC` testing since `Pickit3` is discontinued.

To do that we need the `2FOC` test jig and we've to check if a **new programming cable** is needed.

## Definition of Done
- `ETS` updated and tested
- Churn out a new `IPTS` release 

cc @pattacini @Fabrizio69 @maggia80 @emilianob80

**Comment by davidetome** [comment]
I picked up the new `PicKit4` programmer/debugger.

I tried it and it works w/ the `IPE ` GUI.

Unfortunately, it does not support a standalone `CLI `programming tool as `PicKit3` does.
So I'm looking for a way to avoid adding the entire `MPLAB X IDE `to the new `ETS ` installer.

cc @pattacini @maggia80

**Comment by davidetome** [comment]
added [support](https://github.com/davidetome/electronics-legacy/commit/c05a5c8a6f4572d6d61d15ffc51e2cde47dc646e), to be tested on the real setup

**Comment by davidetome** [comment]
Done w/ this [PR](https://github.com/icub-tech-iit/electronics-legacy/pull/77)

**Comment by pattacini** [comment]
Remember not to post links to private repos into public issues.
